### ISSUE TITLE
Database issues

### ISSUE THREAD

**Issue by SapphireDisD** [SapphireDisD/Ranker#5]
When the bot is offline, the users don't get added to the database. The same happens with old users.
Also, updates to the profile will not be done if the bot is offline.
If there's a need for maintenance (and we have to shut down the bot), some users' profiles may break.
My idea is to create the profile on a message instead and edit it on messages too.

**Comment by dongle-the-gadget** [comment]
Well I tried
```
Rank rank = await _database.GetAsync(e.Author.Id, e.Guild.Id);
rank.Avatar = e.Author.AvatarUrl
rank.Username = e.Author.Username;
rank.Discriminator = e.Author.Discriminator;
rank.Messasges += 1;
```

The `GetAsync` functions for SQLite actually creates an empty `Rank` object if none is found.
```
rank = list.Find(f => f.Id == $"{guildId}/{userId}")?.ToRank() ?? new()
{
  Guild = guildId,
  User = userId
};
```

**Comment by dongle-the-gadget** [comment]
I'll try with another user though and see where it gets me.

**Comment by SapphireDisD** [comment]
Uh, am I wrong? I had an exception when trying to run !rank from line 48 of MessageEvent.cs...

**Comment by dongle-the-gadget** [comment]
Huh. Let me see.

**Comment by dongle-the-gadget** [comment]
> Uh, am I wrong? I had an exception when trying to run !rank from line 48 of MessageEvent.cs...

`!rank` is handled by `Commands.cs`.

**Comment by SapphireDisD** [comment]
I will see if I can see the issue...
I think I may know what happened.

**Comment by SapphireDisD** [comment]
Yep, I had a mixed database file. I'm sorry for opening this issue!

**Comment by SapphireDisD** [comment]
But about the user information update when the bot is offline..?

**Comment by dongle-the-gadget** [comment]
When the bot is offline, yeah it's actually really difficult to do anything.

**Comment by SapphireDisD** [comment]
That's annoying...

**Comment by dongle-the-gadget** [comment]
What do you think about updating them when the bot is immediately online?

**Comment by SapphireDisD** [comment]
Looping through all users?

**Comment by dongle-the-gadget** [comment]
> Looping through all users?

Yes

**Comment by SapphireDisD** [comment]
How much time would it take for 100000 users?

**Comment by SapphireDisD** [comment]
Wait...
If it runs on the background is not that bad of an idea...

**Comment by dongle-the-gadget** [comment]
> How much time would it take for 100000 users?

Idk, and also if we use async it would not be that big of a deal.

**Comment by SapphireDisD** [comment]
Should I implement it..?

**Comment by dongle-the-gadget** [comment]
It's probably a very computationally expensive operation though.
> Dehoist everyone on the server who has a bad name. WARNING: This is a computationally expensive operation.

\- Cliptok

**Comment by SapphireDisD** [comment]
Wait...
Maybe edit the information when running !rank.
Anyway, we just need the information in the database for the leaderboard/users that left.

**Comment by dongle-the-gadget** [comment]
I could only think of username/discriminator/avatar conflict when the user goes to the leaderboard.

**Comment by SapphireDisD** [comment]
Well, if the bot is mostly online, I don't think many conflicts will be created.
And also, if we fix a user when they run !rank, there will be even less.

**Comment by dongle-the-gadget** [comment]
Also one issue: `!rank` could cause the bot to add an XP.

**Comment by SapphireDisD** [comment]
Maybe we should check if it's a command, then ignore it.

**Comment by dongle-the-gadget** [comment]
I think it is not an easy job.

**Comment by dongle-the-gadget** [comment]
But using Slash Commands could work since Slash Commands are counted as "interactions" and not "messages".

**Comment by SapphireDisD** [comment]
I like that idea...

**Comment by dongle-the-gadget** [comment]
Do you think we should send ephemeral message (temporary private messages that last until the user closes Discord) or a DM?

**Comment by SapphireDisD** [comment]
Both sound good. Maybe let the server choose in the JSON?

**Comment by dongle-the-gadget** [comment]
Erisa said in the applicant requirements that rank sends a DM. I think it would be a fair choice.

**Comment by SapphireDisD** [comment]
So let's do that!

**Comment by dongle-the-gadget** [comment]
IIRC DSharpPlus nightly has slash commands implementation, but it looks kinda messy. `IDoEverything.DSharpPlus.SlashCommands` is more tidy

**Comment by SapphireDisD** [comment]
I will see what I can do.

**Comment by dongle-the-gadget** [comment]
Either way it requires DSharpPlus nightly (version 4.2) though, so we would need to add additional restore package managers.

**Comment by SapphireDisD** [comment]
Should we do it..?

**Comment by dongle-the-gadget** [comment]
It would create a difference that `!rank` no longer works, but they could type slash and it would show up as `/rank`

**Comment by dongle-the-gadget** [comment]
And I heard Discord has plans to migrate completely to Slash in April

**Comment by SapphireDisD** [comment]
Well, the users will have to get used to it. But considering the migration, the move makes sense.

**Comment by SapphireDisD** [comment]
But wasn't it only for verified bots?

**Comment by dongle-the-gadget** [comment]
No, anyone could register slash for that matter.

**Comment by SapphireDisD** [comment]
I mean the migration...

**Comment by dongle-the-gadget** [comment]
Oh. Idk.

**Comment by dongle-the-gadget** [comment]
Slash also has input validation so user cannot input an invalid value to `user` parameter.

**Comment by SapphireDisD** [comment]
That's pretty useful...

**Comment by SapphireDisD** [comment]
I will work on it...

**Comment by SapphireDisD** [comment]
I noticed there's a `Exception thrown: 'System.NullReferenceException' in DSharpPlus.dll` on every message and no rank data is created. I will work on it.

**Comment by dongle-the-gadget** [comment]
I did not test it beforehand - I just edited it on GH.

**Comment by dongle-the-gadget** [comment]
And apparently I need to restart VS for it to pick up with the new branch.

**Comment by SapphireDisD** [comment]
I will check.

**Comment by dongle-the-gadget** [comment]
I'll push the new code to GH now.

**Comment by dongle-the-gadget** [comment]
Also if you want to test it I would recommend adding `GuildId` to `config.json` since that will create a guild command (updates immediately) instead of a global command (will be cached for at most an hour)

**Comment by SapphireDisD** [comment]
I'm checking your code. Will replace (parts of) mine.

**Comment by dongle-the-gadget** [comment]
Yeah the new commits have been causing conflicts for mine.

**Comment by SapphireDisD** [comment]
I'm sorry!

**Comment by SapphireDisD** [comment]
Changed!

**Comment by dongle-the-gadget** [comment]
No problem. And btw how about using GuildId field in config?

**Comment by SapphireDisD** [comment]
GuildId is used for slash commands

**Comment by SapphireDisD** [comment]
> Uh, am I wrong? I had an exception when trying to run !rank from line 48 of MessageEvent.cs...

By the way, this happens in every message.

**Comment by dongle-the-gadget** [comment]
Can you change these
```
string username = rank.Username;
string discriminator = rank.Discriminator;
string pfpUrl = rank.Avatar;
```
into these?
```
DiscordUser user = await ctx.Client.GetUserAsync(userId);
string username = rank.Username ?? user.Username;
string discriminator = rank.Discriminator ?? user.Discriminator;
string pfpUrl = rank.Avatar ?? user.AvatarUrl;
```

The current code might cause rank to fail if the user doesn't already exist..

**Comment by dongle-the-gadget** [comment]
> > Uh, am I wrong? I had an exception when trying to run !rank from line 48 of MessageEvent.cs...
> 
> By the way, this happens with every message.

It throws that error every message sent?

**Comment by dongle-the-gadget** [comment]
*or every rank command?

**Comment by SapphireDisD** [comment]
Changed!

**Comment by SapphireDisD** [comment]
> > > Uh, am I wrong? I had an exception when trying to run !rank from line 48 of MessageEvent.cs...
> > 
> > 
> > By the way, this happens with every message.
> 
> It throws that error every message sent?

Every message.

**Comment by SapphireDisD** [comment]
`System.NullReferenceException: Object reference not set to an instance of an object.
   at DSharpPlus.EventArgs.MessageCreateEventArgs.get_Guild()
   at Ranker.MessageEvent.Client_MessageCreated(DiscordClient sender, MessageCreateEventArgs e) in /Users/sapphire/Projects/Ranker/Ranker/Modules/MessageEvent.cs:line 48
   at Emzi0767.Utilities.AsyncEvent`2.InvokeAsync(TSender sender, TArgs e, AsyncEventExceptionMode exceptionMode)`

**Comment by dongle-the-gadget** [comment]
Oh it fails at getting the guild.

**Comment by SapphireDisD** [comment]
I will see what can I do...

**Comment by dongle-the-gadget** [comment]
It seems like DSharpPlus is being finicky and not loading the Guild info for us.

**Comment by SapphireDisD** [comment]
I will check its issues.

**Comment by SapphireDisD** [comment]
I tried to get the channel ID and it fails too. If I remember correctly, if it can't get the channel, it can't get the guild.

**Comment by dongle-the-gadget** [comment]
I tested it in my local machine, it works fine.

**Comment by SapphireDisD** [comment]
I will check my bot intents.

**Comment by SapphireDisD** [comment]
Both enabled but now that I think about it, it's probably unrelated.

**Comment by dongle-the-gadget** [comment]
What permissions did you grant to the bot?

**Comment by SapphireDisD** [comment]
If I remember correctly, read (or was it send?) messages and manage roles. I think I know the issue now, thank you!

**Comment by dongle-the-gadget** [comment]
I actually grant almost all permissions to the bot (since it's generic testing).

**Comment by SapphireDisD** [comment]
What permission do we need for it to work?

**Comment by SapphireDisD** [comment]
I will check the docs.

**Comment by SapphireDisD** [comment]
It doesn't say it requires any permission...

**Comment by dongle-the-gadget** [comment]
View Channels
Read Message History
I think.

**Comment by dongle-the-gadget** [comment]
I'll try stripping permissions from my testing bot and see if it makes any effects.

**Comment by SapphireDisD** [comment]
View Channels + Send Messages + Manage Roles didn't work. Will try adding Read Message History to it as suggested.

**Comment by SapphireDisD** [comment]
Same issue. And I also noticed I was adding Bot role and that role gives it admin. So is not a permissions issue.

**Comment by dongle-the-gadget** [comment]
Oh I reduced it to View Channels and Read MSG History and it still works.

**Comment by SapphireDisD** [comment]
I will try doing a manual request.

**Comment by dongle-the-gadget** [comment]
Also without DirectMessage intent it cannot receive MessageCreated for DMs right?

**Comment by dongle-the-gadget** [comment]
Oh it checks the channel for the guild.

**Comment by SapphireDisD** [comment]
I think Discord may be having issues.

**Comment by dongle-the-gadget** [comment]
Also it's a normal text channel, not threads or something right?

**Comment by SapphireDisD** [comment]
Yes. I did a GET request to https://discord.com/api/guilds/859414636554223626 and success. I did one to https://discord.com/api/guilds/859414636554223626/channels/859414636554223629 and 404.

**Comment by dongle-the-gadget** [comment]
> Yes. I did a GET request to https://discord.com/api/guilds/859414636554223626 and success. I did one to https://discord.com/api/guilds/859414636554223626/channels/859414636554223629 and 404.

It doesn't pick up on the channel?

**Comment by SapphireDisD** [comment]
I think...

**Comment by SapphireDisD** [comment]
I will create a new bot.

**Comment by SapphireDisD** [comment]
No more exception...

**Comment by dongle-the-gadget** [comment]
So might be a tech problem with the previous bot.

**Comment by SapphireDisD** [comment]
Yep. Today some API requests were failing, maybe the issue is returning.

**Comment by dongle-the-gadget** [comment]
It could be a server issue in a geolocation or something.

**Comment by SapphireDisD** [comment]
Well, now that is "fixed" let's continue working. Sorry for wasting your time in something that wasn't really our fault.

**Comment by dongle-the-gadget** [comment]
Haha Discord servers can cause problems sometimes.

**Comment by SapphireDisD** [comment]
Yeah.

**Comment by SapphireDisD** [comment]
By the way, should we close the issue and open discussions?

**Comment by dongle-the-gadget** [comment]
For people who has a problem I guess leave Issues on - for other stuff I would choose Discussions.

**Comment by SapphireDisD** [comment]
No no, I mean to close this issue and chat in discussions instead as this got kind of off-topic.

**Comment by dongle-the-gadget** [comment]
Oh yeah

**Comment by SapphireDisD** [comment]
Well, I guess I'm closing it here.
